=== twitmer/sqlrodeo/src/main/resources/SqlRodeoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SqlRodeoSchema"
	elementFormDefault="unqualified" xmlns:tns="http://www.example.org/SqlRodeoSchema">

	<complexType name="sql-rodeo">
		<sequence>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:properties"></element>
			</choice>
			<choice minOccurs="1" maxOccurs="unbounded">
				<element ref="tns:assign"></element>
				<element ref="tns:close"></element>
				<element ref="tns:commit"></element>
				<element ref="tns:connection"></element>
				<element ref="tns:exit"></element>
				<element ref="tns:if"></element>
				<element ref="tns:include"></element>
				<element ref="tns:objectFactory"></element>
				<element ref="tns:query"></element>
				<element ref="tns:rollback"></element>
				<element ref="tns:sql"></element>
				<element ref="tns:script"></element>
			</choice>
		</sequence>
	</complexType>

	<complexType name="if">
		<choice minOccurs="1" maxOccurs="unbounded">
			<element ref="tns:assign"></element>
			<element ref="tns:close"></element>
			<element ref="tns:commit"></element>
			<element ref="tns:connection"></element>
			<element ref="tns:exit"></element>
			<element ref="tns:if"></element>
			<element ref="tns:include"></element>
			<element ref="tns:objectFactory"></element>
			<element ref="tns:query"></element>
			<element ref="tns:rollback"></element>
			<element ref="tns:sql"></element>
			<element ref="tns:script"></element>
		</choice>
		<attribute name="condition" type="string" use="required"></attribute>
	</complexType>

	<complexType name="query" mixed="true">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:assign"></element>
			<element ref="tns:close"></element>
			<element ref="tns:commit"></element>
			<element ref="tns:connection"></element>
			<element ref="tns:exit"></element>
			<element ref="tns:if"></element>
			<element ref="tns:include"></element>
			<element ref="tns:objectFactory"></element>
			<element ref="tns:query"></element>
			<element ref="tns:rollback"></element>
			<element ref="tns:sql"></element>
			<element ref="tns:script"></element>
		</choice>
		<attribute name="if" type="string"></attribute>
		<attribute name="connection-id" type="string"></attribute>
		<attribute name="publish-as" type="string"></attribute>
		<attribute name="rownum" type="string"></attribute>
		<attribute name="rowcount" type="string"></attribute>
		<attribute name="substitute" type="boolean" default="true"
			use="optional"></attribute>
	</complexType>

	<simpleType name="identifier">
		<restriction base="string">
			<pattern value="[A-Za-z_]([A-Za-z_0-9])*"></pattern>
		</restriction>
	</simpleType>

	<complexType name="sql" mixed="true">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:assign"></element>
			<element ref="tns:close"></element>
			<element ref="tns:commit"></element>
			<element ref="tns:connection"></element>
			<element ref="tns:exit"></element>
			<element ref="tns:if"></element>
			<element ref="tns:include"></element>
			<element ref="tns:objectFactory"></element>
			<element ref="tns:query"></element>
			<element ref="tns:rollback"></element>
			<element ref="tns:sql"></element>
			<element ref="tns:script"></element>
		</choice>
		<attribute name="if" type="string"></attribute>
		<attribute name="connection-id" type="string"></attribute>
		<attribute name="href" type="string"></attribute>
		<attribute name="substitute" type="boolean" default="true"></attribute>
		<attribute name="oneStatement" type="boolean" default="false"></attribute>
	</complexType>

	<complexType name="properties">
		<simpleContent>
			<extension base="string">
				<attribute name="if" type="string"></attribute>
				<attribute name="href" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="objectFactory">
		<simpleContent>
			<extension base="string">
				<attribute name="id" type="tns:identifier" use="required"></attribute>
				<attribute name="name" type="string" use="optional"></attribute>
				<attribute name="factoryClassName" type="string" use="required"></attribute>
				<attribute name="objectClassName" type="string" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="connection">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
		<attribute name="datasource-id" type="tns:identifier" use="required"></attribute>
		<attribute name="autocommit" type="boolean" default="true"></attribute>
	</complexType>

	<complexType name="close">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
	</complexType>

	<complexType name="include">
		<attribute name="if" type="string"></attribute>
		<attribute name="href" type="string" use="required"></attribute>
	</complexType>

	<complexType name="script">
		<simpleContent>
			<extension base="string">
				<attribute name="if" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="commit">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
	</complexType>

	<complexType name="rollback">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
	</complexType>

	<complexType name="assign">
		<attribute name="if" type="string"></attribute>
		<attribute name="id" type="tns:identifier" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>

	<complexType name="exit"></complexType>

	<element name="assign" type="tns:assign"></element>
	<element name="if" type="tns:if"></element>
	<element name="close" type="tns:close"></element>
	<element name="commit" type="tns:commit"></element>
	<element name="connection" type="tns:connection"></element>
	<element name="exit" type="tns:exit"></element>
	<element name="include" type="tns:include"></element>
	<element name="objectFactory" type="tns:objectFactory"></element>
	<element name="properties" type="tns:properties"></element>
	<element name="query" type="tns:query"></element>
	<element name="rollback" type="tns:rollback"></element>
	<element name="script" type="tns:script"></element>
	<element name="sql" type="tns:sql"></element>
	<element name="sql-rodeo" type="tns:sql-rodeo"></element>

</schema>

=== twitmer/sqlrodeo/src/test/resources/schema-rodeo-test.xml
<?xml version="1.0"?>
<!-- 
<GolfCountryClub 
xmlns:tns="http://www.example.org/GolfCountryClub" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/GolfCountryClub GolfCountryClub.xsd ">
-->
<!-- 
<sql-rodeo xmlns="http://www.example.org/SqlRodeoSchema" 
	xmlns:tns="http://www.example.org/SqlRodeoSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/SqlRodeoSchema">
-->
<sql-rodeo 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/SqlRodeoSchema"
	xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">

	<!-- SAD NEWS: Oracle cannot rollback DDL statements, like Create table. 
		See: http://stackoverflow.com/questions/4692690/is-it-possible-to-roll-back-create-table-and-alter-table-statements-in-major-sql -->
	<!-- -->
	<!-- Commits are still useful for DML, so at least there's that. -->

	<datasource id="myConnectionDatasource" name="jdbc/myConnection"
		maxTotal="1" maxIdle="0" maxWaitMillis="1000" driverClassName="oracle.jdbc.OracleDriver"
		url="jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS =  (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))(CONNECT_DATA = (SERVICE_NAME = XE)))"
		username="prowalk" password="prowalk" validationQuery="select 1 from dual" />


	<connection id="myConnection" datasource-id="myConnectionDatasource"/>

	<assign  id="myVar" value="2" />
	<assign id="myJvm" value="sysProps.get('java.version')" />
	<assign id="skipMath" value="50 / 5 + 12" if="myVar > 3" />
	<assign id="someMath" value="50 / ${myVar} + 12" />
	<assign id="initialRelease" value="0" />
	<assign id="initialBuild" value="0" />

	<query connection-id="myConnection" rowcount="versionTableCount">
		SELECT tname from
		tab WHERE tname = 'SCHEMA_VERSION'
	</query>

	<sql connection-id="myConnection" if="versionTableCount == 0">
		CREATE TABLE SCHEMA_VERSION (
		release INT NOT NULL,
		build INT NOT NULL,
		created DATE DEFAULT SYSDATE
		NOT NULL,
		PRIMARY KEY (release, build));

		INSERT INTO
		SCHEMA_VERSION(release, build)
		VALUES (${initialRelease}, ${initialBuild});
	</sql>
<!-- 	<commit id="myConnection"/> -->

	<delegate id="myDelegate" delegate-class="sqlrodeo.DoNothingDelegate">
		Hello delegate!
	</delegate>

	<!-- Determine DB version -->
	<!-- PROBLEM: "release" is reported by db as "release" (all caps), not case-sensitive -->
	<!-- PROBLEM: If Schema_Version is empty, this returns null. -->
	<query connection-id="myConnection" publish-as="release">
		SELECT MAX(release) as release FROM SCHEMA_VERSION
	</query>

	<query connection-id="myConnection" publish-as="build">
		SELECT MAX(build) as build FROM
		SCHEMA_VERSION WHERE release = ${release}
	</query>
	<commit id="myConnection"/>

	<include if="release le 1" href="release-1/release.xml" />
	<commit id="myConnection"/>

<!-- 	<include if="release le 2" href="release-2/release.xml" /> -->
<!-- 	<commit id="myConnection"/> -->

</sql-rodeo>

=== twitmer/sqlrodeo/src/test/resources/big_example/1.x/1.0.x/1.0.0/rodeo.xml
<?xml version="1.0"?>
<sql-rodeo xmlns="http://www.example.org/SqlRodeoSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">

	<!-- Sequences -->
	<sql href="ddl/APP_USER_SEQ.sql" />
	<sql href="ddl/DEPARTMENT_SEQ.sql" />

	<!-- Tables -->
	<sql href="ddl/APP_USER.sql" />
	<sql href="ddl/DEPARTMENT.sql" />

	<!-- Initial data (dml) -->
	<sql href="dml/DEPARTMENT_DATA.sql" />

	<sql>
		INSERT INTO SCHEMA_VERSION(major, minor, patch) VALUES (1, 0, 0);
	</sql>

	<!-- Not needed, but what the hey? -->
	<commit id="myConnection" />

</sql-rodeo>

=== twitmer/sqlrodeo/src/test/resources/hsql/example1/1.x/schema_1.x.xml
<?xml version="1.0"?>
<sql-rodeo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/SqlRodeoSchema" xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">


	<!-- Versions 1.0.x -->
	<include if="schema_version.lessThan('1.0.0')" href="1.0.x/1.0.0/rodeo.xml" />
	<include if="schema_version.lessThan('1.0.1')" href="1.0.x/1.0.1/rodeo.xml" />
	<include if="schema_version.lessThan('1.0.2')" href="1.0.x/1.0.2/rodeo.xml" />
	<include if="schema_version.lessThan('1.0.3')" href="1.0.x/1.0.3/rodeo.xml" />

	<!-- Versions 1.1.x -->
	<include if="schema_version.lessThan('1.1.0')" href="1.1.x/1.1.0/rodeo.xml" />
	<include if="schema_version.lessThan('1.1.1')" href="1.1.x/1.1.1/rodeo.xml" />
	<include if="schema_version.lessThan('1.1.2')" href="1.1.x/1.1.2/rodeo.xml" />
	<include if="schema_version.lessThan('1.1.3')" href="1.1.x/1.1.3/rodeo.xml" />

</sql-rodeo>

=== twitmer/sqlrodeo/src/test/resources/schema_upgrade_counter/master-script.xml
<?xml version="1.0"?>
<sql-rodeo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/SqlRodeoSchema" xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">

	<!-- Import datasource definition. -->
	<properties href="datasource.properties" />

	<!-- Define our datasource and 1 connection. -->
	<objectFactory id="myDataSource" factoryClassName="${db_factoryClassName}"
		objectClassName="${db_objectClassName}">
		database=${db_url}
		user=${db_username}
		password=${db_password}
	</objectFactory>

	<!-- Check out a connection from our DataSource. -->
	<connection id="myConnection" datasource-id="myDataSource" />

	<!-- Determine current schema version. This will create the 'schema_version' 
		table if it doesn't already exist. -->
	<!-- Use HSQL-specific way to determine if the version table exists. -->
	<query connection-id="myConnection" publish-as="versionTableCount">
		SELECT count(table_name) FROM INFORMATION_SCHEMA.SYSTEM_TABLES
		WHERE table_name = 'SCHEMA_VERSION'
	</query>

	<!-- Initialize schema_version table, if it doesn't yet exist. -->
	<sql if="versionTableCount == 0" connection-id="myConnection">
		CREATE TABLE SCHEMA_VERSION (
			version INT NOT NULL,
			PRIMARY KEY (version)
		);
		INSERT INTO SCHEMA_VERSION( version ) VALUES ( 0 );
	</sql>

	<!-- Determine the current DB version. -->
	<query connection-id="myConnection" publish-as="version">
		SELECT MAX(version) FROM SCHEMA_VERSION
	</query>

	<!-- Execute all upgrades for the 1.x line of schema changes -->
	<sql if="version lt 1">
		CREATE TABLE USER
		(
  			ID INTEGER    NOT NULL,
  			NAME VARCHAR(70)  NOT NULL
		);

		CREATE TABLE DEPARTMENT
		(
  			ID INTEGER    NOT NULL,
  			NAME VARCHAR(70)  NOT NULL
		);
		
		INSERT INTO SCHEMA_VERSION( version ) VALUES ( 1 );
	</sql>

	<!-- Execute all upgrades for the 1.x line of schema changes -->
	<include if="version lt 2" href="v2.xml"/>

	<!-- Execute all upgrades for the 1.x line of schema changes -->
	<include if="version lt 3" href="v3.xml"/>

</sql-rodeo>

=== twitmer/sqlrodeo/src/test/resources/big_example/master-script.xml
<?xml version="1.0"?>
<sql-rodeo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/SqlRodeoSchema" xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">

	<!-- Read property files -->
	<properties href="datasource.properties" />

	<!-- Define our datasource and 1 connection. -->
	<objectFactory id="myConnectionDatasource" name="${hsql_db_name}"
		factoryClassName="org.hsqldb.jdbc.JDBCDataSourceFactory"
		objectClassName="org.hsqldb.jdbc.JDBCDataSource">
		database=${hsql_db_url}
		user=${hsql_db_username}
		password=${hsql_db_password}
	</objectFactory>

	<connection id="myConnection" datasource-id="myConnectionDatasource" />

	<!-- Determine current schema version. This will create the 
	'schema_version' table if it doesn't already exist. -->
	<include href="setup_version_table.xml" />

	<!-- Determine the current DB version. -->
	<query connection-id="myConnection" publish-as="major, minor, patch">
		SELECT major, minor, patch FROM SCHEMA_VERSION
		ORDER BY major desc, minor desc, patch desc
		LIMIT 1

		<!-- Use JEXL syntax for instantiating the 'Version' object. -->
		
		<assign id="schema_version" value="new('sqlrodeo.version.Version', '${major}.${minor}.${patch}' )" />
	</query>

	<!-- Execute all upgrades for the 1.x line of schema changes -->
	<include if='schema_version.lessThan( "2.0.0" )' href="1.x/schema_1.x.xml" />

	<!-- Execute all upgrades for the 2.x line of schema changes -->
	<include if='schema_version.lessThan( "3.0.0" )' href="2.x/schema_2.x.xml" />
	
	<script>
	var x = 8;
	var y = 0;
	while (x lt 100) {
		x = x + 2;
		y = y + 1; 
	}
	var z = x + y;
	return x;
	
	</script>

</sql-rodeo>

=== twitmer/sqlrodeo/src/test/resources/schema_upgrade_dottedVersion/master-script.xml
<?xml version="1.0"?>
<sql-rodeo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/SqlRodeoSchema" xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">

	<!-- Import datasource definition. -->
	<properties href="datasource.properties" />

	<!-- Define our datasource and 1 connection. -->
	<objectFactory id="myDataSource" factoryClassName="${db_factoryClassName}"
		objectClassName="${db_objectClassName}">
		database=${db_url}
		user=${db_username}
		password=${db_password}
	</objectFactory>

	<!-- Check out a connection from our DataSource. -->
	<connection id="myConnection" datasource-id="myDataSource" />

	<!-- Determine current schema version. This will create the 'schema_version' 
		table if it doesn't already exist. -->
	<!-- Use HSQL-specific way to determine if the version table exists. -->
	<query connection-id="myConnection" publish-as="versionTableCount">
		SELECT count(table_name) FROM INFORMATION_SCHEMA.SYSTEM_TABLES
		WHERE table_name = 'SCHEMA_VERSION'
	</query>

	<!-- Initialize schema_version table, if it doesn't yet exist. -->
	<sql if="versionTableCount == 0" connection-id="myConnection">
		CREATE TABLE SCHEMA_VERSION (
			major INT NOT NULL,
			minor INT NOT NULL,
			patch INT NOT NULL,
			created TIMESTAMP DEFAULT SYSDATE NOT NULL,
			PRIMARY KEY (major, minor, patch)
		);

		INSERT INTO SCHEMA_VERSION(major, minor, patch) VALUES (0, 0, 0);
	</sql>

	<!-- Determine the current DB version. -->
	<query connection-id="myConnection" publish-as="major, minor, patch">
		SELECT major, minor, patch FROM SCHEMA_VERSION
		ORDER BY major desc, minor desc, patch desc
		LIMIT 1
	</query>

	<!-- Use JEXL syntax for instantiating the 'Version' object. -->
	<assign id="schema_version" value="new('sqlrodeo.version.Version', '${major}.${minor}.${patch}' )" />

	<!-- Create initial schema -->
	<sql if="schema_version.lessThan('1.0.0')">
		CREATE TABLE USER
		(
  			ID INTEGER    NOT NULL,
  			NAME VARCHAR(70)  NOT NULL
		);
		
		CREATE TABLE DEPARTMENT
		(
  			ID INTEGER    NOT NULL,
  			NAME VARCHAR(70)  NOT NULL
		);
		
		INSERT INTO SCHEMA_VERSION(major, minor, patch) VALUES (1, 0, 0);
	</sql>

	<sql if="schema_version.lessThan('1.0.1')">
		ALTER TABLE USER ADD COLUMN EMAIL VARCHAR(70);
		INSERT INTO SCHEMA_VERSION(major, minor, patch) VALUES (1, 0, 1);
	</sql>

	<sql if="schema_version.lessThan('1.1.3')">
		ALTER TABLE USER ADD COLUMN NICKNAME VARCHAR(20);
		
		INSERT INTO USER(ID, Name, Email, Nickname) Values (1, 'Fred', 'fred@example.com', 'Freddy');
		
		INSERT INTO SCHEMA_VERSION(major, minor, patch) VALUES (1, 1, 3);
	</sql>

</sql-rodeo>
