=== twitmer/sqlrodeo/sqlrodeo/src/main/resources/SqlRodeoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SqlRodeoSchema"
	elementFormDefault="unqualified" xmlns:tns="http://www.example.org/SqlRodeoSchema">

	<complexType name="sql-rodeo">
		<sequence>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:properties"></element>
			</choice>
			<choice minOccurs="1" maxOccurs="unbounded">
				<element ref="tns:datasource"></element>
				<element ref="tns:connection"></element>
				<element ref="tns:close"></element>
				<element ref="tns:query"></element>
				<element ref="tns:assign"></element>
				<element ref="tns:sql"></element>
				<element ref="tns:include"></element>
				<element ref="tns:delegate"></element>
				<element ref="tns:commit"></element>
				<element ref="tns:rollback"></element>
				<element ref="tns:exit"></element>
			</choice>
		</sequence>
	</complexType>

	<complexType name="query" mixed="true">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:datasource"></element>
			<element ref="tns:connection"></element>
			<element ref="tns:close"></element>
			<element ref="tns:query"></element>
			<element ref="tns:assign"></element>
			<element ref="tns:sql"></element>
			<element ref="tns:include"></element>
			<element ref="tns:delegate"></element>
			<element ref="tns:commit"></element>
			<element ref="tns:rollback"></element>
			<element ref="tns:exit"></element>
		</choice>
		<attribute name="if" type="string"></attribute>
		<attribute name="connection-id" type="string"></attribute>
		<attribute name="publish-as" type="string"></attribute>
		<attribute name="rownum" type="string"></attribute>
		<attribute name="rowcount" type="string"></attribute>
		<attribute name="substitute" type="boolean" default="true"
			use="optional"></attribute>
	</complexType>

	<simpleType name="identifier">
		<restriction base="string">
			<pattern value="[A-Za-z_]([A-Za-z_0-9])*"></pattern>
		</restriction>
	</simpleType>

	<complexType name="sql" mixed="true">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:datasource"></element>
			<element ref="tns:connection"></element>
			<element ref="tns:close"></element>
			<element ref="tns:query"></element>
			<element ref="tns:assign"></element>
			<element ref="tns:sql"></element>
			<element ref="tns:include"></element>
			<element ref="tns:delegate"></element>
			<element ref="tns:commit"></element>
			<element ref="tns:rollback"></element>
			<element ref="tns:exit"></element>
		</choice>
		<attribute name="if" type="string"></attribute>
		<attribute name="connection-id" type="string"></attribute>
		<attribute name="href" type="string"></attribute>
		<attribute name="substitute" type="boolean" default="true"></attribute>
		<attribute name="oneStatement" type="boolean" default="false"></attribute>
	</complexType>

	<complexType name="properties">
		<simpleContent>
			<extension base="string">
				<attribute name="if" type="string"></attribute>
				<attribute name="href" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="datasource">
		<attribute name="href" type="string"></attribute>
		<attribute name="id" type="tns:identifier" use="required"></attribute>
		<attribute name="name" type="string"></attribute>
		<attribute name="defaultAutoCommit" type="string"></attribute>
		<attribute name="defaultReadOnly" type="string"></attribute>
		<attribute name="defaultTransactionIsolation" type="string"></attribute>
		<attribute name="defaultCatalog" type="string"></attribute>
		<attribute name="cacheState" type="string"></attribute>
		<attribute name="driverClassName" type="string"></attribute>
		<attribute name="lifo" type="string"></attribute>
		<attribute name="maxTotal" type="string"></attribute>
		<attribute name="maxIdle" type="string"></attribute>
		<attribute name="minIdle" type="string"></attribute>
		<attribute name="initialSize" type="string"></attribute>
		<attribute name="maxWaitMillis" type="string"></attribute>
		<attribute name="testOnCreate" type="string"></attribute>
		<attribute name="testOnBorrow" type="string"></attribute>
		<attribute name="testOnReturn" type="string"></attribute>
		<attribute name="timeBetweenEvictionRunsMillis" type="string"></attribute>
		<attribute name="numTestsPerEvictionRun" type="string"></attribute>
		<attribute name="minEvictableIdleTimeMillis" type="string"></attribute>
		<attribute name="softMinEvictableIdleTimeMillis" type="string"></attribute>
		<attribute name="evictionPolicyClassName" type="string"></attribute>
		<attribute name="testWhileIdle" type="string"></attribute>
		<attribute name="password" type="string"></attribute>
		<attribute name="url" type="string"></attribute>
		<attribute name="username" type="string"></attribute>
		<attribute name="validationQuery" type="string"></attribute>
		<attribute name="validationQueryTimeout" type="string"></attribute>
		<attribute name="jmxName" type="string"></attribute>
		<attribute name="connectionInitSqls" type="string"></attribute>
		<attribute name="accessToUnderlyingConnectionAllowed" type="string"></attribute>
		<attribute name="removeAbandonedOnBorrow" type="string"></attribute>
		<attribute name="removeAbandonedOnMaintenance" type="string"></attribute>
		<attribute name="removeAbandonedTimeout" type="string"></attribute>
		<attribute name="logAbandoned" type="string"></attribute>
		<attribute name="poolPreparedStatements" type="string"></attribute>
		<attribute name="maxOpenPreparedStatements" type="string"></attribute>
		<attribute name="connectionProperties" type="string"></attribute>
		<attribute name="maxConnLifetimeMillis" type="string"></attribute>
		<attribute name="rollbackOnReturn" type="string"></attribute>
		<attribute name="enableAutoCommitOnReturn" type="string"></attribute>
		<attribute name="defaultQueryTimeout" type="string"></attribute>
	</complexType>

	<complexType name="connection">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
		<attribute name="datasource-id" type="tns:identifier" use="required"></attribute>
		<attribute name="autocommit" type="boolean" default="true"></attribute>
	</complexType>

	<complexType name="close">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
	</complexType>

	<complexType name="include">
		<attribute name="if" type="string"></attribute>
		<attribute name="href" type="string" use="required"></attribute>
	</complexType>

	<complexType name="delegate">
		<simpleContent>
			<extension base="string">
				<attribute name="if" type="string"></attribute>
				<attribute name="id" type="tns:identifier" use="required"></attribute>
				<attribute name="delegate-class" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="commit">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
	</complexType>

	<complexType name="rollback">
		<attribute name="id" type="tns:identifier" use="required"></attribute>
	</complexType>

	<complexType name="assign">
		<attribute name="if" type="string"></attribute>
		<attribute name="id" type="tns:identifier" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>

	<complexType name="exit"></complexType>

	<element name="sql-rodeo" type="tns:sql-rodeo"></element>
	<element name="query" type="tns:query"></element>
	<element name="sql" type="tns:sql"></element>
	<element name="properties" type="tns:properties"></element>
	<element name="datasource" type="tns:datasource"></element>
	<element name="connection" type="tns:connection"></element>
	<element name="close" type="tns:close"></element>
	<element name="include" type="tns:include"></element>
	<element name="delegate" type="tns:delegate"></element>
	<element name="commit" type="tns:commit"></element>
	<element name="rollback" type="tns:rollback"></element>
	<element name="assign" type="tns:assign"></element>

	<element name="exit" type="tns:exit"></element>

</schema>

=== twitmer/sqlrodeo/sqlrodeo/src/test/resources/hsql/example1/hsql-test.xml
<?xml version="1.0"?>
<sql-rodeo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/SqlRodeoSchema" xsi:schemaLocation="http://www.example.org/SqlRodeoSchema SqlRodeoSchema.xsd">

	<properties href="props.properties" />
	<properties href="hsql-datasource.properties" />

	<properties>
		c=3
		d=4
	</properties>
	<properties />

	<!-- TODO: Meaningful to have more than 1 connection for a HSQLDB db? -->
	<datasource id="myConnectionDatasource" name="${hsql_db_name}"
		maxTotal="${hsql_db_maxTotal}" maxIdle="${hsql_db_maxIdle}" maxWaitMillis="${hsql_db_maxWaitMillis}"
		url="${hsql_db_url}" username="${hsql_db_username}" password="${hsql_db_password}" />

	<connection id="myConnection" datasource-id="myConnectionDatasource" />

	<assign id="initialRelease" value="0" />
	<assign id="initialBuild" value="0" />

	<delegate id="myDelegate" delegate-class="sqlrodeo.DoNothingDelegate">
		Hello delegate!
	</delegate>


	<query connection-id="myConnection" rowcount="versionTableCount">
		SELECT table_name
		from
		INFORMATION_SCHEMA.SYSTEM_TABLES WHERE table_name =
		'SCHEMA_VERSION'
	</query>

	<sql connection-id="myConnection" if="versionTableCount == 0">
		CREATE TABLE SCHEMA_VERSION (
		release INT NOT NULL,
		build INT NOT NULL,
		created DATE DEFAULT SYSDATE
		NOT NULL,
		PRIMARY KEY (release, build));

		INSERT INTO
		SCHEMA_VERSION(release, build)
		VALUES (${initialRelease},
		${initialBuild});
	</sql>
	<!-- <commit id="myConnection"/> -->

	<!-- Determine DB version -->
	<query connection-id="myConnection" publish-as="release">
		SELECT
		MAX(release) as release FROM SCHEMA_VERSION
	</query>

	<query connection-id="myConnection" publish-as="build">
		SELECT MAX(build)
		as build FROM
		SCHEMA_VERSION WHERE release = ${release}
	</query>

	<include if="release le 1" href="release1.xml" />
	<commit id="myConnection" />

	<exit></exit>

</sql-rodeo>
